name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${pwd}
          cd src | zip -r douban_book_metadata.zip ../a.zip *
