name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/src | zip -r douban_book_metadata.zip ${GITHUB_WORKSPACE}/a.zip *
